### ISSUE TITLE
NPE caused by deleted and redacted elements

### ISSUE THREAD

**Issue by simonpoole** [zedlabs/ElementHistoryDialog#1]
A history with deleted and redacted elements will cause a NPE when invoking the compare screen.

See https://www.openstreetmap.org/node/1/history for an example of this. 

I would suggest that the current status of the element needs to be displayed in the comparison, that is visible/deleted and if the changeset was redacted.

**Comment by zedlabs** [comment]
I think the reason was that I was passing the element with the list position instead of the actual version number, fixed it in this [commit](https://github.com/zedlabs/ElementHistoryDialog/commit/75337a1ea520ef799188d0bdcd935ed50516a2a8).

Need to test for the redacted changeset elements, haven't been able to recreate it
